// Set testEnv to "production" to test production code(lib/, which is generated by run
// `yarn build` or `npm run build`)
// Or set testEnv "dev" to test development code(src/)
const testEnv = "dev";
export default testEnv;
